- name: Execute bash file and output content
  hosts: all
  gather_facts: false

  tasks:

    - name: Fetch bash file
      copy:
        src: ../bash/spec-report.sh
        dest: /tmp/spec-report.sh
        mode: 0644
      register: fetch_result

    - name: Execute bash file
      shell: bash /tmp/spec-report.sh > /tmp/spec-report.txt
      when: fetch_result.changed

    - name: Output content to file on Ansible controller from remote host
      fetch:
        src: /tmp/spec-report.txt
        dest: '{{ inventory_hostname }}-spec-report.txt'
        flat: yes
      when: fetch_result.changed